# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

[tools]
rust = "1.59.0"
"cargo:bacon" = "3.7.0"
"cargo:cargo-about" = "0.6.6"
"cargo:cargo-audit" = "0.22.1"
hk = "1.36.0"
pkl = "0.30.2"
"cargo:cargo-llvm-cov" = "0.6.21"
"cargo:cargo-toml-lint" = "0.1.1"
cocogitto = "6.5.0"
gitleaks = "8.30.0"
java = "25.0.1"
mdbook = "0.5.2"
"pipx:reuse" = "6.2.0"
"pipx:texthooks" = "0.7.1"
taplo = "0.10.0"
vale = "3.13.0"
yamllint = "1.37.1"
